-- 1. Insert Users
INSERT INTO users (username, code, role, sales_count, extra_hours) VALUES
('aracelit', 'A955118', 'admin', 0, 0),
('diegou', 'D1455', 'admin', 0, 0),
('joacor', '955118', 'admin', 0, 0),
('gastonv', '955602', 'admin', 0, 0),
('ignaciop', '605955', 'admin', 0, 0)
ON CONFLICT (username) DO NOTHING;

-- 2. Insert Products
INSERT INTO products (id, name, price, category, description, stock, image_url, colors, variants, location) VALUES
('ip14-128', 'iPhone 14 128GB', 590, 'iPhone', 'Apple iPhone 14. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_14_128gb.png', null, null, null),
('ip15-128', 'iPhone 15 128GB', 670, 'iPhone', 'Dynamic Island. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_15_128gb.png', null, null, null),
('ip15-256', 'iPhone 15 256GB', 800, 'iPhone', 'Dynamic Island. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_15_128gb.png', null, null, null),
('ip15p-128', 'iPhone 15 Plus 128GB', 780, 'iPhone', 'Pantalla Grande. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_15_plus_512gb.png', null, null, null),
('ip15p-512', 'iPhone 15 Plus 512GB', 880, 'iPhone', 'Máxima capacidad. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_15_plus_512gb.png', null, null, null),
('ip16e-128', 'iPhone 16E 128GB', 640, 'iPhone', 'Nueva Edición. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16e_128gb.png', null, null, null),
('ip16e-256', 'iPhone 16E 256GB', 750, 'iPhone', 'Nueva Edición. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16e_256gb.png', null, null, null),
('ip16-128', 'iPhone 16 128GB', 790, 'iPhone', 'A18 Chip. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16_128gb.png', null, null, null),
('ip16-256', 'iPhone 16 256GB', 880, 'iPhone', 'A18 Chip. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16_256gb.png', null, null, null),
('ip16pl-128', 'iPhone 16 Plus 128GB', 880, 'iPhone', 'Gran Pantalla. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16_plus_128gb.png', null, null, null),
('ip16pl-256', 'iPhone 16 Plus 256GB', 1000, 'iPhone', 'Gran Pantalla. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16_plus_256gb.png', null, null, null),
('ip16pro-128', 'iPhone 16 Pro 128GB', 1080, 'iPhone', 'Titanium. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16_pro_128gb.png', null, null, null),
('ip16promax-256', 'iPhone 16 Pro Max 256GB', 1330, 'iPhone', 'Solo Desert Titanium. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_16_pro_max_256gb_desert.png', null, null, null),
('ip17-256', 'iPhone 17 256GB', 990, 'iPhone', 'White, Blue, Lavender, Sage. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_256gb_blue.png', ARRAY['White', 'Blue', 'Lavender', 'Sage'], null, null),
('ip17air-256', 'iPhone 17 Air 256GB', 980, 'iPhone', 'Ultra Thin. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_air_256gb_black.png', ARRAY['Black', 'White', 'Blue', 'Gold'], null, null),
('ip17pro-256-og', 'iPhone 17 Pro 256GB (Orange)', 1330, 'iPhone', 'Titanium Orange. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_256gb_orange.png', null, null, null),
('ip17pro-256-bl', 'iPhone 17 Pro 256GB (Blue)', 1340, 'iPhone', 'Titanium Blue. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_256gb_blue.png', null, null, null),
('ip17pro-256-sl', 'iPhone 17 Pro 256GB (Silver)', 1350, 'iPhone', 'Titanium Silver. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_256gb_silver.png', null, null, null),
('ip17pro-512-og', 'iPhone 17 Pro 512GB (Orange)', 1530, 'iPhone', 'Titanium Orange. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_512gb_orange.png', null, null, null),
('ip17pro-512-bl', 'iPhone 17 Pro 512GB (Blue)', 1540, 'iPhone', 'Titanium Blue. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_512gb_blue.png', null, null, null),
('ip17pro-512-sl', 'iPhone 17 Pro 512GB (Silver)', 1540, 'iPhone', 'Titanium Silver. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_512gb_silver.png', null, null, null),
('ip17pro-1tb', 'iPhone 17 Pro 1TB', 1760, 'iPhone', 'Orange, Blue, Silver. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_1tb_silver.png', ARRAY['Orange', 'Blue', 'Silver'], null, null),
('ip17pm-256-og', 'iPhone 17 Pro Max 256GB (Orange)', 1420, 'iPhone', 'Max Orange. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_256gb_orange.png', null, null, null),
('ip17pm-256-bl', 'iPhone 17 Pro Max 256GB (Blue)', 1430, 'iPhone', 'Max Blue. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_256gb_blue.png', null, null, null),
('ip17pm-256-sl', 'iPhone 17 Pro Max 256GB (Silver)', 1430, 'iPhone', 'Max Silver. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_256gb_silver.png', null, null, null),
('ip17pm-512-og', 'iPhone 17 Pro Max 512GB (Orange)', 1640, 'iPhone', 'Max Orange. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_512gb_orange.png', null, null, null),
('ip17pm-512-bl', 'iPhone 17 Pro Max 512GB (Blue)', 1670, 'iPhone', 'Max Blue. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_512gb_blue.png', null, null, null),
('ip17pm-512-sl', 'iPhone 17 Pro Max 512GB (Silver)', 1670, 'iPhone', 'Max Silver. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_512gb_silver.png', null, null, null),
('ip17pm-1tb', 'iPhone 17 Pro Max 1TB', 1910, 'iPhone', 'Orange, Blue, Silver. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_1tb_silver.png', ARRAY['Orange', 'Blue', 'Silver'], null, null),
('ip17pm-2tb', 'iPhone 17 Pro Max 2TB', 2300, 'iPhone', 'Orange, Blue, Silver. Incluye: Funda, Glass, Cargador y Auriculares de regalo!', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/iphone_17_pro_max_2tb_silver.png', ARRAY['Orange', 'Blue', 'Silver'], null, null),
('mac-air-m2-13', 'MacBook Air M2 13"', 1040, 'MacBook', '256GB - Midnight', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('mac-air-m2-15', 'MacBook Air M2 15"', 1300, 'MacBook', '256GB - Midnight', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('mac-air-m3-13', 'MacBook Air M3 13"', 1232, 'MacBook', '256GB - Starlight', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('mac-air-m3-15', 'MacBook Air M3 15"', 1458, 'MacBook', '256GB - Midnight', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('mac-pro-m3-14', 'MacBook Pro 14" M3', 1797, 'MacBook', '512GB - Space Gray', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('mac-pro-m3pro-14', 'MacBook Pro 14" M3 Pro', 2249, 'MacBook', '512GB - Space Black', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('mac-pro-m3pro-16', 'MacBook Pro 16" M3 Pro', 2814, 'MacBook', '512GB - Space Black', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('imac-m3', 'iMac 24" M3', 1458, 'MacBook', '8-Core GPU, 256GB Green', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ipad-9', 'iPad 9na Gen 64GB', 339, 'iPad', 'Space Gray', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ipad-10', 'iPad 10ma Gen 64GB', 441, 'iPad', 'Blue / Pink / Yellow', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ipad-air-m2-11', 'iPad Air 11" M2 64GB', 667, 'iPad', 'Blue / Purple', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ipad-air-m2-13', 'iPad Air 13" M2 128GB', 893, 'iPad', 'Starlight', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ipad-pro-m4-11', 'iPad Pro 11" M4 256GB', 1119, 'iPad', 'Standard Glass', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ipad-pro-m4-13', 'iPad Pro 13" M4 256GB', 1458, 'iPad', 'Standard Glass', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('aw-se2-40', 'Apple Watch SE 2 40mm', 282, 'Watch', 'GPS - Starlight', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('aw-se2-44', 'Apple Watch SE 2 44mm', 316, 'Watch', 'GPS - Midnight', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('aw-s9-41', 'Apple Watch S9 41mm', 451, 'Watch', 'GPS - Varios Colores', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('aw-s9-45', 'Apple Watch S9 45mm', 485, 'Watch', 'GPS - Varios Colores', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('aw-u2', 'Apple Watch Ultra 2', 903, 'Watch', 'Titanium', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-a06', 'Samsung A06 64GB', 115, 'Samsung', 'Entry Level', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/A06_black-removebg-preview.png', null, null, null),
('sam-a07', 'Samsung A07 64GB', 130, 'Samsung', 'Entry Level', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/a07_black-removebg-preview.png', null, null, null),
('sam-a16', 'Samsung A16 128GB', 185, 'Samsung', 'Básico Potente', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/A16_gris-removebg-preview.png', null, null, null),
('sam-a17', 'Samsung A17 256GB', 280, 'Samsung', '5G', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-a26', 'Samsung A26 256GB', 280, 'Samsung', '5G', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-a36-128', 'Samsung A36 128GB', 320, 'Samsung', 'Mid Range', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/a36_white-removebg-preview.png', null, null, null),
('sam-a36-256', 'Samsung A36 256GB', 350, 'Samsung', 'Mid Range+', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/a36_white-removebg-preview.png', null, null, null),
('sam-a56-128', 'Samsung A56 128GB', 420, 'Samsung', 'Premium Mid', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-a56-256', 'Samsung A56 256GB', 430, 'Samsung', 'Premium Mid+', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-s25', 'Samsung S25 256GB', 740, 'Samsung', 'Flagship Compact', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-s25fe', 'Samsung S25 FE 256GB', 700, 'Samsung', 'Fan Edition', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-s25p-256', 'Samsung S25+ 256GB', 870, 'Samsung', 'Plus Size', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-s25p-512', 'Samsung S25+ 512GB', 910, 'Samsung', 'Plus Size Max', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-s25u-256', 'Samsung S25 Ultra 256GB', 1050, 'Samsung', 'S-Pen Titanio', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-s25u-512', 'Samsung S25 Ultra 512GB', 1140, 'Samsung', 'S-Pen Titanio', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('sam-s25u-1tb', 'Samsung S25 Ultra 1TB', 1290, 'Samsung', 'S-Pen Titanio', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('xiao-redmi-14', 'Xiaomi Redmi 14', 180, 'Xiaomi', 'Nuevo Modelo', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/redmi14-removebg-preview.png', null, null, null),
('xiao-14c', 'Xiaomi Redmi 14C', 150, 'Xiaomi', 'Budget King', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/redmi_14c_black-removebg-preview.png', null, null, null),
('xiao-14-pro', 'Xiaomi 14 Pro', 400, 'Xiaomi', 'Pro Performance', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/redmi14_pro_2-removebg-preview.png', null, null, null),
('xiao-14-pro-plus', 'Xiaomi 14 Pro Plus', 480, 'Xiaomi', 'Flagship Killer', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/SamXia/redmi_14_pro_plus_azul-removebg-preview.png', null, null, null),
('xiao-rn13', 'Xiaomi Redmi Note 13 256GB', 230, 'Xiaomi', '108MP Camera', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('xiao-rn13p', 'Xiaomi Redmi Note 13 Pro', 320, 'Xiaomi', '200MP OIS', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('xiao-rn13p-plus', 'Xiaomi Redmi Note 13 Pro+', 450, 'Xiaomi', 'Curved Screen, IP68', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('xiao-poco-x6', 'Xiaomi Poco X6 256GB', 320, 'Xiaomi', 'Snapdragon 7s Gen 2', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('xiao-poco-x6p', 'Xiaomi Poco X6 Pro 512GB', 395, 'Xiaomi', 'Dimensity 8300 Ultra', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ps5-dig-noj', 'PS5 Digital (Sin Juegos)', 540, 'Gaming', 'Sony PlayStation 5 Slim', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_digital__sin_juegos_.png', null, null, null),
('ps5-dig-j', 'PS5 Digital (Con Juegos)', 560, 'Gaming', 'Returnal + Ratchet Clank', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_digital__con_juegos_.png', null, null, null),
('ps5-fis-j1', 'PS5 Física (Con Juegos 1)', 620, 'Gaming', 'Returnal + Ratchet Clank', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_f_sica__con_juegos_.png', null, null, null),
('ps5-fis-j2', 'PS5 Física (Con Juegos 2)', 660, 'Gaming', 'Gran Turismo 7 + Astrobot', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_f_sica__con_juegos_.png', null, null, null),
('ps5-pro', 'PS5 Pro Digital 2TB', 895, 'Gaming', 'La más potente', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_pro_digital_2tb__sin_juego_.png', null, null, null),
('sw2', 'Nintendo Switch 2', 670, 'Gaming', 'Nueva Generación', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/nintendo_switch_2.png', null, null, null),
('sw2-mk', 'Nintendo Switch 2 + Mario Kart', 690, 'Gaming', 'Bundle Mario Kart', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/nintendo_switch_2___juego_mario_kart.png', null, null, null),
('xbox-x', 'Xbox Series X 1TB', 850, 'Gaming', 'Microsoft 4K', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/xbox_x_1tb.png', null, null, null),
('xbox-s-1tb', 'Xbox Series S 1TB', 660, 'Gaming', 'Carbon Black', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/xbox_s_1tb.png', null, null, null),
('xbox-s-512', 'Xbox Series S 512GB', 560, 'Gaming', 'Robot White', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('mq3s-128', 'Meta Quest 3S 128GB', 495, 'Gaming', 'VR Accesible', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_vr2___horizon.png', null, null, null),
('mq3s-256', 'Meta Quest 3S 256GB', 560, 'Gaming', 'Mayor capacidad', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_vr2___horizon.png', null, null, null),
('mq3-512', 'Meta Quest 3 512GB', 750, 'Gaming', 'Mixed Reality Pro', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_vr2___horizon.png', null, null, null),
('gm-cod', 'Call of Duty: Black Ops 6', 50, 'Gaming', 'Primaria PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('gm-gta', 'GTA V', 45, 'Gaming', 'Primaria PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('gm-f1', 'F1 24', 45, 'Gaming', 'Primaria PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('gm-rdr2', 'Red Dead Redemption 2', 40, 'Gaming', 'Primaria PS4/PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('gm-tlou', 'The Last of Us Remastered', 25, 'Gaming', 'Primaria PS4/PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('gm-mc', 'Minecraft', 30, 'Gaming', 'Primaria PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('gm-db', 'Dragon Ball Sparking! Zero', 60, 'Gaming', 'Primaria PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('gm-nba', 'NBA 2K25', 50, 'Gaming', 'Primaria PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('lap-asus-zen', 'Asus Zenbook 14 OLED', 1085, 'Laptops', 'i5 / 8GB / 512GB', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('lap-hp-pav', 'HP Pavilion 15', 893, 'Laptops', 'Ryzen 5 / 16GB / 512GB', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('lens-canon-50', 'Canon EF 50mm f/1.8', 193, 'Accesorios', 'STM Lens', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('lens-sony-85', 'Sony FE 85mm f/1.8', 701, 'Accesorios', 'Portrait Lens', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('dji-mini-3', 'DJI Mini 3', 577, 'Accesorios', 'Drone con control RC-N1', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('dji-mini-3-fly', 'DJI Mini 3 Fly More', 831, 'Accesorios', 'Combo 3 Baterías', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('dual-sense', 'Joystick Dual Sense', 100, 'Accesorios', 'Original PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/joystick_dual_sense.png', null, null, null),
('g29', 'Volante Logitech G29', 360, 'Accesorios', 'PC/PS', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/volante_logitech_g29.png', null, null, null),
('vr2', 'PS5 VR2 + Horizon', 630, 'Accesorios', 'Realidad Virtual PS5', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/Prod2/ps5_vr2___horizon.png', null, null, null),
('ap4', 'AirPods 4', 193, 'Accesorios', 'Sin cancelación', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('ap4-anc', 'AirPods 4 ANC', 249, 'Accesorios', 'Con cancelación activa', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('app2', 'AirPods Pro 2 USB-C', 260, 'Accesorios', 'USB-C MagSafe', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('app3', 'AirPods Pro 3', 339, 'Accesorios', 'Nuevo modelo', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('jbl-go4', 'JBL GO 4', 50, 'Accesorios', 'Portable', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/jbl/jbl_go4.png', null, null, null),
('jbl-flip7', 'JBL FLIP 7', 140, 'Accesorios', 'Waterproof', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/jbl/jbl_flip_7.png', null, null, null),
('jbl-ch6', 'JBL CHARGE 6', 200, 'Accesorios', 'Powerbank', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/jbl/jbl_charge_6.png', null, null, null),
('jbl-bb4', 'JBL BOOMBOX 4', 600, 'Accesorios', 'Massive Sound', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/lxtlogo.png', null, null, null),
('jbl-pb710', 'JBL PARTYBOX 710', 800, 'Accesorios', 'Fiesta Total', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/jbl/jbl_partybox_710.png', null, null, null),
('jbl-tour', 'JBL Tour Pro 2', 190, 'Accesorios', 'Smart Case', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/jbl/jbl_tour_pro_2.png', null, null, null),
('jbl-520', 'JBL TUNE 520BT', 65, 'Accesorios', 'Purple, Black', true, 'https://jecxqmertgnogjetodao.supabase.co/storage/v1/object/public/LXT2/jbl/jbl_tune_520bt.png', null, null, null)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  price = EXCLUDED.price,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  stock = EXCLUDED.stock,
  image_url = EXCLUDED.image_url,
  colors = EXCLUDED.colors;
